#ifndef CodeResource_h
#define CodeResource_h

/******************************演奏代码******************************/
const static char8_t *c8NoteFuncCode[] =
{
	u8"c4();",
	u8"d4();",
	u8"e4();",
	u8"f4();",
	u8"g4();",

	u8"a4();",
	u8"b4();",
	u8"c5();",
	u8"d5();",
	u8"e5();",

	u8"f5();",
	u8"g5();",
	u8"a5();",
	u8"b5();",
	u8"c6();",

	u8"",
};

const static char8_t *c8TimeFuncCode[] =
{
	u8"t1();",
	u8"t2();",
	u8"t4();",
};

const static char8_t *c8VarCode[] =
{
	u8"var time=",/*0*/u8";",
	u8"var time2=",/*2*/u8";",
	u8"var time4=",/*4*/u8";",
	u8"var pressoffset=",/*6*/u8";",
	u8"var pressoffset2=",/*8*/u8";",
};

const static char8_t *c8BaseCode[] =
{
	u8"var stop=1;",
	u8"var speedControl=1;",
	u8"var zuobiaoPath = \"/sdcard/Download/SkyMsToJs/zuobiao.txt\";\n",
	u8"if (files.exists(zuobiaoPath)) {eval(files.read(zuobiaoPath));}else{setScreenMetrics(1080, 2340);var x=[780,975,1170,1365,1560];var y=[215,410,605];}\n",
};

const static char8_t *c8RandomCode[] =
{
	u8"function ran() {return Math.random()*pressoffset2-pressoffset;}",
	u8"function c4() {press(x[0]+ran(),y[0]+ran(),1);}",
	u8"function d4() {press(x[1]+ran(),y[0]+ran(),1);}",
	u8"function e4() {press(x[2]+ran(),y[0]+ran(),1);}",
	u8"function f4() {press(x[3]+ran(),y[0]+ran(),1);}",
	u8"function g4() {press(x[4]+ran(),y[0]+ran(),1);}",
	u8"function a4() {press(x[0]+ran(),y[1]+ran(),1);}",
	u8"function b4() {press(x[1]+ran(),y[1]+ran(),1);}",
	u8"function c5() {press(x[2]+ran(),y[1]+ran(),1);}",
	u8"function d5() {press(x[3]+ran(),y[1]+ran(),1);}",
	u8"function e5() {press(x[4]+ran(),y[1]+ran(),1);}",
	u8"function f5() {press(x[0]+ran(),y[2]+ran(),1);}",
	u8"function g5() {press(x[1]+ran(),y[2]+ran(),1);}",
	u8"function a5() {press(x[2]+ran(),y[2]+ran(),1);}",
	u8"function b5() {press(x[3]+ran(),y[2]+ran(),1);}",
	u8"function c6() {press(x[4]+ran(),y[2]+ran(),1);}",
};

const static char8_t *c8NoRandomCode[] =
{
	u8"function c4() {press(x[0],y[0],1);}",
	u8"function d4() {press(x[1],y[0],1);}",
	u8"function e4() {press(x[2],y[0],1);}",
	u8"function f4() {press(x[3],y[0],1);}",
	u8"function g4() {press(x[4],y[0],1);}",
	u8"function a4() {press(x[0],y[1],1);}",
	u8"function b4() {press(x[1],y[1],1);}",
	u8"function c5() {press(x[2],y[1],1);}",
	u8"function d5() {press(x[3],y[1],1);}",
	u8"function e5() {press(x[4],y[1],1);}",
	u8"function f5() {press(x[0],y[2],1);}",
	u8"function g5() {press(x[1],y[2],1);}",
	u8"function a5() {press(x[2],y[2],1);}",
	u8"function b5() {press(x[3],y[2],1);}",
	u8"function c6() {press(x[4],y[2],1);}",
};

const static char8_t *c8WindowCode[] =
{
	u8"var window = floaty.window(<frame><vertical><button id=\"btn\" text=\'开始\'/><horizontal><button id=\"speedLow\" text=\'减速\' w=\"80\"/><button id=\"speedHigh\" text=\'加速\' w=\"80\"/></horizontal><horizontal><button id=\"speed\" text=\'1.0x\' w=\"80\"/><button id=\"stop\" text=\'停止\' w=\"80\"/></horizontal></vertical></frame>);",
	u8"window.exitOnClose();",
	u8"window.btn.click(()=>{if(stop) {stop = 0;window.btn.setText(\'暂停\');}else{stop = 1;window.btn.setText(\'继续\');}})",
	u8"window.speedHigh.click(()=>{speedControl=(speedControl*10+1)/10;window.speed.setText(speedControl+\'x\');})",
	u8"window.speedLow.click(()=>{if(speedControl<=0.1){return;}speedControl=(speedControl*10-1)/10;window.speed.setText(speedControl+\'x\');})",
	u8"window.speed.click(()=>{speedControl=1;window.speed.setText(speedControl+\'x\');})",
	u8"window.stop.click(()=>{engines.stopAll();})",
	u8"function start() {while (stop) {sleep(100);}}",
	u8"function t1() {while (stop) {sleep(100)}sleep(time/speedControl);}",
	u8"function t2() {while (stop) {sleep(100)}sleep(time2/speedControl);}",
	u8"function t4() {while (stop) {sleep(100)}sleep(time4/speedControl);}",
	u8"start();",
};

const static char8_t *c8NoWindowCode[] =
{
	u8"function t1() {sleep(time);}",
	u8"function t2() {sleep(time2);}",
	u8"function t4() {sleep(time4);}",
	u8"sleep(",/*3*/u8");",
};
/******************************演奏代码******************************/

/******************************辅助代码******************************/

const static char8_t *c8KeyCalibrationCode[] =//按键校准s
{
	u8R"CODE(try {)CODE",
	u8R"CODE(    runControl();)CODE",
	u8R"CODE(    auto.waitFor();)CODE",
	u8R"CODE(    alert("按音量下键开始获取坐标；按音量上键停止脚本！"))CODE",
	u8R"CODE(    //toasts("按下 音量- 可以切换");)CODE",
	u8R"CODE(    events.observeKey();)CODE",
	u8R"CODE(    events.on("key", function(k, e) {)CODE",
	u8R"CODE(        let ek = k * 10 + e.getAction();)CODE",
	u8R"CODE(        switch (ek) {)CODE",
	u8R"CODE(            case 241:)CODE",
	u8R"CODE(                log("volume_up up");)CODE",
	u8R"CODE(                toast("已停止"))CODE",
	u8R"CODE(                engines.stopAll();)CODE",
	u8R"CODE(                break)CODE",
	u8R"CODE()CODE",
	u8R"CODE(            case 250:)CODE",
	u8R"CODE(                // log("volume_down down");)CODE",
	u8R"CODE(                event.emit("touchable");)CODE",
	u8R"CODE(                break)CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(        ek = 0;)CODE",
	u8R"CODE(    });)CODE",
	u8R"CODE()CODE",
	u8R"CODE(    var event = events.emitter();)CODE",
	u8R"CODE(    event.on("touchable", function() {)CODE",
	u8R"CODE(        touchable_state = !touchable_state;)CODE",
	u8R"CODE(        x.setTouchable(touchable_state);)CODE",
	u8R"CODE(        if (touchable_state) {)CODE",
	u8R"CODE(            toasts("现在请按压第1个按键"))CODE",
	u8R"CODE(        } else {)CODE",
	u8R"CODE(            toasts("坐标获取结束");)CODE",
	u8R"CODE(            engines.stopAll();)CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(    });)CODE",
	u8R"CODE(    var num = 1)CODE",
	u8R"CODE(    var zuobiao = [])CODE",
	u8R"CODE(    let path = "/sdcard/Download/SkyMsToJs/zuobiao.txt")CODE",
	u8R"CODE(    var x = floaty.rawWindow()CODE",
	u8R"CODE(            <frame id="but" bg="#00000000"/>)CODE",
	u8R"CODE(        ),)CODE",
	u8R"CODE(        touchable_state = false;)CODE",
	u8R"CODE(    x.setSize(-1, -1);)CODE",
	u8R"CODE(    x.setTouchable(touchable_state);)CODE",
	u8R"CODE(    x.but.setOnTouchListener(function(v, e) {)CODE",
	u8R"CODE(        switch (e.getAction()) {)CODE",
	u8R"CODE(            case e.ACTION_DOWN:)CODE",
	u8R"CODE(                toasts(e.getRawX().toFixed(0) + " , " + e.getRawY().toFixed(0));)CODE",
	u8R"CODE(                zuobiao[num - 1] = [e.getRawX().toFixed(0), e.getRawY().toFixed(0)])CODE",
	u8R"CODE(                num = num + 1)CODE",
	u8R"CODE(                break)CODE",
	u8R"CODE(            case e.ACTION_MOVE:)CODE",
	u8R"CODE(                toasts(e.getRawX().toFixed(0) + " , " + e.getRawY().toFixed(0));)CODE",
	u8R"CODE(                break)CODE",
	u8R"CODE(            case e.ACTION_UP:)CODE",
	u8R"CODE(                if (num < 16) {)CODE",
	u8R"CODE(                    toasts("现在请按压第" + num + "个按键"))CODE",
	u8R"CODE(                    // toasts(e.getRawX().toFixed(0) + " , " + e.getRawY().toFixed(0));)CODE",
	u8R"CODE(                } else {)CODE",
	u8R"CODE(                    toast("坐标获取完毕！"))CODE",
	u8R"CODE(                    let xs = [];)CODE",
	u8R"CODE(                    let ys = [];)CODE",
	u8R"CODE(                    for (var i = 0; i <= 4; i++) {)CODE",
	u8R"CODE(                        xs.push(((Number(zuobiao[i][0]) + Number(zuobiao[i + 5][0]) + Number(zuobiao[i + 10][0])) / 3).toFixed(0)))CODE",
	u8R"CODE(                    })CODE",
	u8R"CODE(                    for (var i = 0; i <= 14; i = i + 5) {)CODE",
	u8R"CODE(                        ys.push(((Number(zuobiao[i][1]) + Number(zuobiao[i + 1][1]) + +Number(zuobiao[i + 2][1]) + Number(zuobiao[i + 3][1]) + Number(zuobiao[i + 4][1])) / 5).toFixed(0)))CODE",
	u8R"CODE(                    })CODE",
	u8R"CODE(                    files.createWithDirs(path))CODE",
	u8R"CODE(                    files.write(path, "x=[" + xs + "]\ny=[" + ys + "]");)CODE",
	u8R"CODE(                    engines.stopAll();)CODE",
	u8R"CODE(                })CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(        return true;)CODE",
	u8R"CODE(    });)CODE",
	u8R"CODE()CODE",
	u8R"CODE(} catch (e) {)CODE",
	u8R"CODE(    log(e);)CODE",
	u8R"CODE(})CODE",
	u8R"CODE()CODE",
	u8R"CODE(// 脚本引擎运行控制函数)CODE",
	u8R"CODE(// runControl(true) 重新启动本脚本)CODE",
	u8R"CODE(// runControl(false) 保留本脚本已经在运行的脚本引擎，停止本次脚本引擎运行)CODE",
	u8R"CODE(// runControl() 若本脚本已经在运行，则停止本脚本所有正在运行的脚本引擎)CODE",
	u8R"CODE(function runControl(stop) {)CODE",
	u8R"CODE(    let arr = engines.all(),)CODE",
	u8R"CODE(        me = engines.myEngine(),)CODE",
	u8R"CODE(        run = true;)CODE",
	u8R"CODE(    for (i in arr) {)CODE",
	u8R"CODE(        if (arr[i].getSource().toString() == me.getSource().toString() && arr[i] != me) {)CODE",
	u8R"CODE(            if (stop != false) arr[i].forceStop();)CODE",
	u8R"CODE(            run = stop == true;)CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(    if (!run) exit();)CODE",
	u8R"CODE(})CODE",
	u8R"CODE()CODE",
	u8R"CODE(// toast通知代替函数)CODE",
	u8R"CODE(function toasts(text, time) {)CODE",
	u8R"CODE(    text = text || null;)CODE",
	u8R"CODE(    time = time || 5000;)CODE",
	u8R"CODE(    if (isNaN(time)) return;)CODE",
	u8R"CODE(    let arr = engines.all(),)CODE",
	u8R"CODE(        run = false;)CODE",
	u8R"CODE(    for (i in arr) {)CODE",
	u8R"CODE(        if (files.getName(arr[i].getSource()) == "toast.js") {)CODE",
	u8R"CODE(            run = true;)CODE",
	u8R"CODE(            break;)CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(    if (!run) {)CODE",
	u8R"CODE(        let tex = "var t = toasts();\nevents.broadcast.on(\"toast\", (arr) => {\nif (arr.length != 2) return;\nlet time = new Number(arr[1][1]),text = arr[1][0];\nif(isNaN(time)) time = 5000;\nif(!text) return;\nt(text, time);});\nsetInterval(() => {}, 10000);\nfunction toasts() {\nvar th = \"\",Y = device.width / 4,X = Y,x = Y * 2;\nvar flo = floaty.rawWindow(\n<frame gravity=\"center\" bg=\"#00000000\">\n<text id=\"message\"  bg=\"#70000000\" textColor=\"#ffffff\" textSize=\"15sp\" gravity=\"center\" w=\"auto\" padding=\"1\"/>\n</frame>);\nflo.setTouchable(false);\nflo.setSize(0, 0);\nreturn doflo;\nfunction doflo(mes, time) {\nmes = \" \" + mes.toString().split(\"\\n\").join(\" \\n \") + \" \";\nif (th != \"\") {\nth.interrupt();\nth = \"\";}\nui.run(function() {\nflo.message.setText(mes);});\nflo.setPosition(X, Y);\nflo.setSize(x, -2);\nth = threads.start(function() {\nsleep(time);\nui.run(function() {\nflo.message.setText(\"\");});\nflo.setSize(0, 0);\nth = \"\";});}}";)CODE",
	u8R"CODE(        engines.execScript("toast", tex);)CODE",
	u8R"CODE(        sleep(500);)CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(    // log(text);)CODE",
	u8R"CODE(    events.broadcast.emit("toast", [)CODE",
	u8R"CODE(        [engines.myEngine(), [text, time]])CODE",
	u8R"CODE(    ]);)CODE",
	u8R"CODE(})CODE",
};


const static char8_t *c8DirectlyPlayScoreCode[] =//直接演奏乐谱
{
	u8R"CODE("auto")CODE",
	u8R"CODE(var arr = [];)CODE",
	u8R"CODE(var time;)CODE",
	u8R"CODE(var score;)CODE",
	u8R"CODE(var zuobiaoPath = "/sdcard/Download/SkyMsToJs/zuobiao.txt";)CODE",
	u8R"CODE(if (files.exists(zuobiaoPath)) {)CODE",
	u8R"CODE(    eval(files.read(zuobiaoPath));)CODE",
	u8R"CODE(} else {)CODE",
	u8R"CODE(    setScreenMetrics(1080, 2340);)CODE",
	u8R"CODE(    x=[780, 975, 1170, 1365, 1560];)CODE",
	u8R"CODE(    y=[215, 410, 605];)CODE",
	u8R"CODE(};)CODE",
	u8R"CODE(var sheetPath = "/storage/emulated/0/光遇乐谱/" //默认乐谱存放路径)CODE",
	u8R"CODE()CODE",
	u8R"CODE(function getScore() {)CODE",
	u8R"CODE(    files.ensureDir(sheetPath))CODE",
	u8R"CODE(    data = files.listDir(sheetPath))CODE",
	u8R"CODE(    let showNames = [];)CODE",
	u8R"CODE(    for (i = 0; i < data.length; i++) {)CODE",
	u8R"CODE(        if (data[i].search(".txt") != -1) {)CODE",
	u8R"CODE(            showNames.push(data[i]);)CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(    if (showNames.length == 0) {)CODE",
	u8R"CODE(        alert("请将乐谱文件存放在该路径下：" + sheetPath))CODE",
	u8R"CODE(        exit())CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(    let choose = dialogs.select("选择乐谱", showNames);)CODE",
	u8R"CODE(    if (choose != -1) {)CODE",
	u8R"CODE(        data = files.read(sheetPath + showNames[choose], encoding = "utf-16"))CODE",
	u8R"CODE(        data = JSON.parse(data)[0])CODE",
	u8R"CODE(        var myScore = {};)CODE",
	u8R"CODE(        myScore.name = data.name;)CODE",
	u8R"CODE(        myScore.author = data.author;)CODE",
	u8R"CODE(        myScore.score = change(data.songNotes);)CODE",
	u8R"CODE(        play(myScore);)CODE",
	u8R"CODE(    } else {)CODE",
	u8R"CODE(        toast("你没有选谱子"))CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(})CODE",
	u8R"CODE()CODE",
	u8R"CODE(function change(score) {)CODE",
	u8R"CODE(    let finalScore = [];)CODE",
	u8R"CODE(    let partScore = {};)CODE",
	u8R"CODE(    let pitchesDuration = 0;)CODE",
	u8R"CODE(    let now,)CODE",
	u8R"CODE(        nowTime,)CODE",
	u8R"CODE(        nowPitches,)CODE",
	u8R"CODE(        lastTime = 0;)CODE",
	u8R"CODE(    for (i = 0; i < score.length; i++) {)CODE",
	u8R"CODE(        now = score[i];)CODE",
	u8R"CODE(        nowTime = now.time;)CODE",
	u8R"CODE(        nowPitches = now.key;)CODE",
	u8R"CODE(        nowPitches = nowPitches.slice(4, nowPitches.length))CODE",
	u8R"CODE(        partScore.pitches = nowPitches;)CODE",
	u8R"CODE(        pitchesDuration = Number(nowTime) - Number(lastTime);)CODE",
	u8R"CODE(        partScore.time = pitchesDuration;)CODE",
	u8R"CODE(        finalScore.push(partScore);)CODE",
	u8R"CODE(        partScore = {}; //important)CODE",
	u8R"CODE(        lastTime = nowTime;)CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(    return finalScore;)CODE",
	u8R"CODE(})CODE",
	u8R"CODE()CODE",
	u8R"CODE(function play(myScore) {)CODE",
	u8R"CODE(    //暂停功能)CODE",
	u8R"CODE(    var s = 0;)CODE",
	u8R"CODE(    var speedControl = 1.0;)CODE",
	u8R"CODE(    var window = floaty.window(<frame>)CODE",
	u8R"CODE(    <vertical>)CODE",
	u8R"CODE(    <button id="btn" text='继续'/>)CODE",
	u8R"CODE(    <horizontal>)CODE",
	u8R"CODE(    <button id="speedLow" text='减速'/>)CODE",
	u8R"CODE(    <button id="speedHigh" text='加速'/>)CODE",
	u8R"CODE(    </horizontal>)CODE",
	u8R"CODE(    <button id="stop" text='停止'/>)CODE",
	u8R"CODE(    </vertical></frame>);)CODE",
	u8R"CODE(    window.exitOnClose();)CODE",
	u8R"CODE(    window.btn.click(() => {)CODE",
	u8R"CODE(        if (window.btn.getText() != '暂停') {)CODE",
	u8R"CODE(            s = 1;)CODE",
	u8R"CODE(            window.btn.setText('暂停'))CODE",
	u8R"CODE(        } else {)CODE",
	u8R"CODE(            s = 0;)CODE",
	u8R"CODE(            window.btn.setText('继续'))CODE",
	u8R"CODE(        })CODE",
	u8R"CODE(    });)CODE",
	u8R"CODE(    window.speedHigh.click(() => {)CODE",
	u8R"CODE(        speedControl = speedControl + 0.1)CODE",
	u8R"CODE(        toast("当前速度：x"+speedControl))CODE",
	u8R"CODE(    }))CODE",
	u8R"CODE(    window.speedLow.click(() => {)CODE",
	u8R"CODE(        speedControl = speedControl - 0.1)CODE",
	u8R"CODE(        toast("当前速度：x"+speedControl))CODE",
	u8R"CODE(    }))CODE",
	u8R"CODE(    window.stop.click(() => {)CODE",
	u8R"CODE(        engines.stopAll())CODE",
	u8R"CODE(    }))CODE",
	u8R"CODE(    toast("正在弹奏：" + myScore.name))CODE",
	u8R"CODE(    let score = myScore.score;)CODE",
	u8R"CODE(    for (let i = 0; i < score.length; i++) {)CODE",
	u8R"CODE(        while (s != 1) {)CODE",
	u8R"CODE(            sleep(100))CODE",
	u8R"CODE(        }; //暂停功能)CODE",
	u8R"CODE(        sleep(score[i].time / speedControl);)CODE",
	u8R"CODE(        strToxy(score[i].pitches);)CODE",
	u8R"CODE(        press(arr[0], arr[1], 1);)CODE",
	u8R"CODE(    })CODE",
	u8R"CODE(})CODE",
	u8R"CODE()CODE",
	u8R"CODE(function strToxy(pitches) {)CODE",
	u8R"CODE(    arr = [];)CODE",
	u8R"CODE(    arr[0] = x[Number(pitches) % 5];)CODE",
	u8R"CODE(    arr[1] = y[Math.trunc(Number(pitches) / 5)];)CODE",
	u8R"CODE(})CODE",
	u8R"CODE()CODE",
	u8R"CODE(getScore();)CODE",
	u8R"CODE(exit();)CODE",
};


/******************************辅助代码******************************/

#endif // CodeResource_h